services:
  - type: web
    name: chatbot-fastapi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PYTHONPATH
        value: .
      - key: CHATBOT_MONGO_URI
        sync: false
      - key: CHATBOT_DB_NAME
        value: chatbot_support
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_VERIFY_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
  - type: worker
    name: cakebot-scheduler
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: LOG_LEVEL
        value: INFO
    startCommand: python scheduler.py
