services:
  - type: web
    name: cakebot-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ZALO_ACCESS_TOKEN
        sync: false
      - key: ZALO_VERIFY_TOKEN
        sync: false
      - key: FACEBOOK_PAGE_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_VERIFY_TOKEN
        sync: false
      - key: API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
  - type: worker
    name: cakebot-scheduler
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: LOG_LEVEL
        value: INFO
    startCommand: python scheduler.py
